name: build
on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v5
        with:
          persist-credentials: false
      - name: Validate Gradle Wrapper
        uses: gradle/actions/wrapper-validation@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: 21
          check-latest: true
      - name: Build with Gradle
        run: ./gradlew build
      - name: Upload Fabric Artifacts to GitHub
        uses: actions/upload-artifact@v4
        with:
          name: Fabric-git
          path: fabric/build/libs/ConfigManager-fabric*
      - name: Upload NeoForge Artifacts to GitHub
        uses: actions/upload-artifact@v4
        with:
          name: NeoForge-git
          path: /build/libs/ConfigManager-neoforge*